# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_SOC_EXYNOS9830) += \
	exynos990-r8s_eur_open_00.dtbo \
	exynos990-r8s_eur_open_02.dtbo \
	exynos990-r8s_eur_open_05.dtbo \
	exynos990-x1s_eur_open_05.dtbo \
	exynos990-x1s_eur_open_16.dtbo \
	exynos990-x1s_eur_open_17.dtbo \
	exynos990-x1s_eur_open_19.dtbo \
	exynos990-x1s_eur_open_21.dtbo \
	exynos990-y2s_eur_open_04.dtbo \
	exynos990-y2s_eur_open_05.dtbo \
	exynos990-y2s_eur_open_06.dtbo \
	exynos990-y2s_eur_open_16.dtbo \
	exynos990-y2s_eur_open_17.dtbo \
	exynos990-y2s_eur_open_18.dtbo \
	exynos990-y2s_eur_open_19.dtbo \
	exynos990-y2s_eur_open_21.dtbo \
	exynos990-z3s_eur_open_16.dtbo \
	exynos990-z3s_eur_open_17.dtbo \
	exynos990-z3s_eur_open_18.dtbo \
	exynos990-z3s_eur_open_20.dtbo \
	exynos990-z3s_eur_open_21.dtbo \
	exynos990-z3s_eur_open_22.dtbo \
	exynos990-z3s_eur_open_24.dtbo

always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb*
